ignore newline
indutny/entropoetry pull request #1
Opened 2017-05-02 19:53 UTC by gyulaweber

Hey,
I think it would be nice to ignore newline, so I've created this PR, what do you think?

2017-05-02 19:56 UTC, indutny requested changes

2017-05-02 19:56 UTC, indutny commented on lib/ui.js
> -    buf = Buffer.from(key, 'hex');
I think we should ignore spaces too, then! Would you care to add this too?

Minor nit: please use single quotes.

2017-05-02 20:01 UTC, gyulaweber commented on lib/ui.js
> -    buf = Buffer.from(key, 'hex');
sure! :)

2017-05-03 01:15 UTC, indutny commented
Landed and released, thank you!

2017-05-03 01:15 UTC, closed without merging